[build]
base = "tpDSW/frontend"
command = "npm run build"
publish = "tpDSW/frontend/build"

[build.environment]
REACT_APP_API_URL = "https://backend-birbnb.onrender.com"
CI = "false"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
